# Generated by Django 3.2.5 on 2023-05-01 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='members',
            field=models.ManyToManyField(related_name='houses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contestant',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finale.house'),
        ),
        migrations.AddField(
            model_name='contestant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contestant', to=settings.AUTH_USER_MODEL),
        ),
    ]
