# Generated by Django 4.2 on 2023-04-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_manager', '0002_remove_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='rank_checkpoint',
            field=models.IntegerField(default=0),
        ),
    ]
